import "@/style/global.css"
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
//layour envuelve nuestras rutas
////children englobamos todas las rutas hijas y si agregamos algo aca todas las rutas lo tendran
export const metadata = {
  title: 'Estudio Juridico DA',
  description: 'Generated by create next app',
}

export default function RootLayout({children}:{children: React.ReactNode}) 
{
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>{children}</body> 
    </html>
  )
}
